[app]
limit = 15
prefork = false
strictRouting = true
caseSensitive = true
unescapePath = true

[middleware]
cache = true
compress = true
logger = true
recover = true

[server]
host = "localhost"
port = "5050"
token = "123456789"

[socket]
origins = ["*"]
readBufferSize = 2048
writeBufferSize = 2048

[spotify]
clientID = "#{SPOTIFY_CLIENT_ID}"
clientSecret = "#{SPOTIFY_CLIENT_SECRET}"
refreshToken = "#{SPOTIFY_REFRESH_TOKEN}"
